version: "3"

volumes:
  conversa_dj_local_postgres_data: {}
  conversa_dj_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: conversa_dj_local_django
    container_name: conversa_dj_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: conversa_dj_production_postgres
    container_name: conversa_dj_local_postgres
    volumes:
      - conversa_dj_local_postgres_data:/var/lib/postgresql/data:Z
      - conversa_dj_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5433:5432"

  docs:
    image: conversa_dj_local_docs
    container_name: conversa_dj_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./conversa_dj:/app/conversa_dj:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: conversa_dj_local_redis
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    image: conversa_dj_local_celeryworker
    container_name: conversa_dj_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: conversa_dj_local_celerybeat
    container_name: conversa_dj_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: conversa_dj_local_flower
    container_name: conversa_dj_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
